### ISSUE TITLE
Topup with amount x showing 2x balance

### ISSUE THREAD

**Issue by ssandeep** [maticnetwork/heimdall#676]
Call topUpForFee in the contract for amount 1000matic, you will see that the balance is increased to 2000matic:
```
ubuntu@ip-192-168-0-118:~/heimdall$ ./build/heimdalld q bank balances 0x2a0EdEE1996EfadaDE184355B59aA9E8Eb532319
balances:
- amount: "2000000000000000000000"
  denom: matic
pagination:
  next_key: null
  total: "0"
```
